server:
  port: 8888

spring:
  application:
    name: Libre-Admin
  profiles:
    active: dev
  redis:
    host: 172.25.131.19
    port: 6379


mybatis-plus:
  type-aliases-package: com.libre.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      table-underline: true
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

libre:
  redis:
    serializer-type: protostuff

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine # 还支持：linkedhashmap
      keyConvertor: bean:jacksonKeyConvertor
  remote:
    default:
      type: redis
      keyConvertor: bean:jacksonKeyConvertor
      valueEncoder: bean:jacksonValueEncoder # 支持：kryo、java
      valueDecoder: bean:jacksonValueDecoder # 支持：kryo、java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}


