server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: libre
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.libre.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      table-underline: true
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
