server:
  port: 9876

spring:
  application:
    name: Libre-Admin
  config:
    location: config
  profiles:
    active: prod
  mvc:
    path-match:
      matching-strategy: ant_path_matcher


mybatis-plus:
  type-aliases-package: com.libre.admin.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      table-underline: true
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false


libre:
  security:
    permit-all:
      - /auth/token
      - /auth/captcha
    jwt-token:
      secret: 669da4ca0fde3928856705c8746512daa9957b91b0bbe855790b561d9f08be80

logging:
  file:
    path: './logs/'

