server:
  port: 9876

spring:
  application:
    name: Libre
  profiles:
    active: dev
    include: quartz
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: Libre
  flyway:
    enabled: true
    locations:
      - classpath:db/postgres
    baseline-on-migrate: true
    clean-disabled: true
    baseline-version: 0
  rsocket:
    server:
      port: 18090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      table-underline: true
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

logging:
  file:
    path: './logs/'

security:
  oauth2:
    ignore:
      urls:
        - /druid/**
        - /favicon.ico
        - /error
        - /static/**
        - /webjars*
        - /webjars/**
        - /upload/**
        - /swagger-resources/**
        - /v3/api-docs
        - /v3/api-docs/swagger-config
        - /doc.html
        - /swagger-ui/**
        - /api/openapi/**
        - /file/**
        - /chat/**
        - /chat
        - /api/**


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/libre
    username: libre
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 500
      min-idle: 50
      max-wait: 100000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
  cache:
    redis:
      time-to-live: 2h
      key-prefix: "libre:"
  mail:
    host: smtp.163.com
    password: ESAHXBZHJYQRYLAR
    username: librezc@163.com
    port: 465

libre:
  redisson:
    single:
      address: 127.0.0.1:6379
  xss:
    enabled: false
  redis:
    serializer-type: jdk
  captcha:
    enabled: true
  swagger:
    enabled: false
  oss:
    endpoint: http://101.42.252.139:9090
    bucket-name: libre
    access-key: libre
    secret-key: 894659968
  file:
    upload-path: /Users/libre/video/
  chat:
    token: Bearer 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

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/libre
    username: xxxxxxx
    password: xxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 500
      min-idle: 50
      max-wait: 100000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
  cache:
    redis:
      time-to-live: 2h
      key-prefix: "libre:"
  data:
    redis:
      host: 127.0.0.1
      jedis:
        pool:
          enabled: true
          min-idle: 5
          max-active: 10
          max-idle: 10
          max-wait: 5

libre:
  xss:
    enabled: false
  redis:
    serializer-type: json
  captcha:
    enabled: true
  swagger:
    enabled: false

logging:
  level:
    org.springframework: trace