spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.42.252.139:6033/libre
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 500
      min-idle: 50
      max-wait: 100000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
  cache:
    redis:
      time-to-live: 2h
      key-prefix: "libre:"
  redis:
    host: 101.42.252.139
    password: zc504879189..

libre:
  xss:
    enabled: false
  redis:
    serializer-type: json
  security:
    jwt-token:
      secret: 669da4ca0fde3928856705c8746512daa9957b91b0bbe855790b561d9f08be80
  captcha:
    enabled: true
  swagger:
    enabled: false

#jetcache:
#  statIntervalMinutes: 1
#  areaInCacheName: false
#  local:
#    default:
#      type: caffeine # 还支持：linkedhashmap
#      keyConvertor: bean:protostuffKeyConvertor
#  remote:
#    default:
#      type: redis
#      keyConvertor: bean:protostuffKeyConvertor
#      valueEncoder: bean:protostuffValueEncoder # 支持：kryo、java
#      valueDecoder: bean:protostuffValueDecoder # 支持：kryo、java
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${spring.redis.host}
#      port: ${spring.redis.port}
