spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 504879189
  cache:
    redis:
      time-to-live: 2h
      key-prefix: "libre:"

libre:
  xss:
    enabled: true
    mode: escape
  redis:
    serializer-type: protostuff



#jetcache:
#  statIntervalMinutes: 1
#  areaInCacheName: false
#  local:
#    default:
#      type: caffeine # 还支持：linkedhashmap
#      keyConvertor: bean:protostuffKeyConvertor
#  remote:
#    default:
#      type: redis
#      keyConvertor: bean:protostuffKeyConvertor
#      valueEncoder: bean:protostuffValueEncoder # 支持：kryo、java
#      valueDecoder: bean:protostuffValueDecoder # 支持：kryo、java
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${spring.redis.host}
#      port: ${spring.redis.port}
